# Generated by Django 3.2.13 on 2022-05-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blockeds',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followings',
        ),
    ]
