# Generated by Django 3.2.13 on 2022-05-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_spoiler_checked',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_spoiler_self',
        ),
        migrations.RemoveField(
            model_name='review',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='review',
            name='spoiler_check_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
