# Generated by Django 3.2.9 on 2021-11-25 05:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tmdb_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('tmdb_rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(max_length=100)),
                ('tmdb_id', models.IntegerField()),
                ('video_key', models.CharField(max_length=100)),
                ('adult', models.BooleanField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('recommend_users', models.ManyToManyField(related_name='recommend_movies', to=settings.AUTH_USER_MODEL)),
                ('wish_users', models.ManyToManyField(related_name='wish_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
